repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: uptime-kuma
    url: https://dirsigler.github.io/uptime-kuma-helm
bases:
  - environments.yaml
---
templates:
  default:
    missingFileHandler: Error
    values:
      - values.yaml.gotmpl
releases:
  - name: prometheusstack
    installed: false
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: "75.10.0"
    inherit:
      - template: default
  - name: uptime-kuma
    installed: true
    namespace: monitoring
    chart: uptime-kuma/uptime-kuma
    version: "2.21.3"
    inherit:
      - template: default
