repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
bases:
  - environments.yaml
---
templates:
  default:
    missingFileHandler: Error
    values:
      - values.yaml.gotmpl
releases:
  - name: prometheusstack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: "75.10.0"
    inherit:
      - template: default
